apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        {{- if .Values.deployment.recreatePodsOnEachRelease }}
        date: {{ now | quote }}
        {{- end }}
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.deployment.image }}
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_URLS
              value: http://*:{{ .Values.deployment.port }}
          ports:
            - name: myapp
              containerPort: 80
          livenessProbe:
            httpGet:
              port: 80
              path: /healthz