apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: myapp
      port: {{ .Values.service.port }}
      targetPort: myapp
      nodePort: 31935
    - name: prometheus
      port: 8889
      targetPort: prometheus
      nodePort: 31562