apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command:
        - sleep
        - "3600"
      imagePullPolicy: Always
  restartPolicy: Always