receivers:
  otlp:
    protocols:
      grpc:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    metric_expiration: 30s
    send_timestamps: true

service:
  pipelines:
    metrics:
      receivers: [ otlp ]
      exporters: [ prometheus ]