receivers:
  otlp:
    protocols:
      grpc:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

processors:
  transform:
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["biba"], resource.attributes["biba"])

service:
  pipelines:
    metrics:
      receivers: [ otlp ]
      processors: [ transform ]
      exporters: [ prometheus ]