version: 3

tasks:
  default: task --list
  port-forward:
    desc: Port forward all services
    deps: [prometheus, grafana]
  prometheus:
    desc: Port forward prometheus service
    cmds:
      - kubectl port-forward service/prometheus-kube-prometheus-prometheus 9090:9090
  grafana:
    desc: Port forward grafana service
    cmds:
      - kubectl port-forward service/prometheus-grafana 3000:3000
  minikube:
    desc: Restart minikube
    cmds:
      - minikube delete
      - |
        minikube start \
        --extra-config=kubelet.authentication-token-webhook=true \
        --extra-config=kubelet.authorization-mode=Webhook \
        --extra-config=scheduler.address=0.0.0.0 \
        --extra-config=controller-manager.address=0.0.0.0