fullnameOverride: prometheus

prometheus:
  fullnameOverride: prometheus
  service:
    type: NodePort
    nodePort: 31235
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 5Gi

grafana:
  fullnameOverride: grafana
  replicas: 1
  grafana.ini:
    database:
      type: postgres
      name: grafana
  service:
    type: NodePort
    port: 3000
    nodePort: 31647

alertmanager:
  fullnameOverride: alertmanager
  alertmanagerSpec:
    alertmanagerConfigMatcherStrategy:
      type: None
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 5Gi
    alertmanagerConfigSelector:
      matchLabels:
        release: prometheus