fullnameOverride: prometheus

prometheus:
  fullnameOverride: prometheus
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: [ "ReadWriteMany" ]
          resources:
            requests:
              storage: 5Gi
  service:
    type: LoadBalancer

grafana:
  fullnameOverride: grafana
  service:
    type: LoadBalancer
    port: 3000

alertmanager:
  fullnameOverride: alertmanager
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: [ "ReadWriteMany" ]
          resources:
            requests:
              storage: 5Gi