fullnameOverride: prometheus

prometheus:
  fullnameOverride: prometheus
  service:
    type: NodePort
    nodePort: 31235
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 5Gi

grafana:
  fullnameOverride: grafana
  service:
    type: NodePort
    port: 3000
    nodePort: 31647

alertmanager:
  fullnameOverride: alertmanager
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 5Gi